.TH "VecGFX::Mat3::MRow" 3 "Wed Jun 5 2024" "VecGFX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VecGFX::Mat3::MRow \- A class holding a row from a \fBMat3\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mat\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float & \fBoperator[]\fP (int idx)"
.br
.RI "Index into this row to get the value at the column with the given index\&. "
.ti -1c
.RI "float const & \fBoperator[]\fP (int index) const"
.br
.RI "Index into this row to get the value at the column with the given index\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMat3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class holding a row from a \fBMat3\fP class\&. 
.SH "Member Function Documentation"
.PP 
.SS "float & VecGFX::Mat3::MRow::operator[] (int idx)"

.PP
Index into this row to get the value at the column with the given index\&. 
.PP
\fBParameters\fP
.RS 4
\fIidx\fP The column index to get the value of 
.RE
.PP
\fBReturns\fP
.RS 4
The retrieved value 
.RE
.PP

.SS "float const  & VecGFX::Mat3::MRow::operator[] (int index) const"

.PP
Index into this row to get the value at the column with the given index\&. 
.PP
\fBParameters\fP
.RS 4
\fIidx\fP The column index to get the value of 
.RE
.PP
\fBReturns\fP
.RS 4
The retrieved value 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for VecGFX from the source code\&.
